version: "3.3"
services:

  nodered:
    image: nodered/node-red
    networks:
     - mynet
    environment:
    - SERVICE_NAME=node-red
    ports:
     - "80:1880"
    # volumes:
    # - ${PWD}/node-red/modules:/root/.node-red
    links:
    - mosquitto
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
     - mynet
networks:
  mynet:
      driver: bridge
      driver_opts:
          com.docker.network.enable_ipv6: "true"